# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

tone_instructions: Enforce all rules from BEST_PRACTICES.md strictly. For every violation, cite line numbers, explain the issue, provide corrected code, and reference the guideline section.

knowledge_base:
  opt_out: false
  learnings:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/BEST_PRACTICES.md"
      - "**/best_practices.md"
      - "**/Best_Practices.md"

reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  
  path_filters:
    - "!**/settings.json"
    - "!**/*.meta"
    - "!**/Library/**"
    - "!**/Temp/**"
    - "!**/Logs/**"
  
  path_instructions:
    - path: "**/*.cs"
      instructions: Review this C# file strictly against BEST_PRACTICES.md. For each violation found, cite line numbers, explain the issue, provide corrected code, and reference the guideline section.
