# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

tone_instructions: |
  Enforce ALL rules and guidelines from BEST_PRACTICES.md strictly and comprehensively.
  
  Review every aspect of the code against ALL sections, principles, guidelines, rules, code examples, and patterns documented in BEST_PRACTICES.md. Check for violations of every rule documented, regardless of which section it appears in.
  
  For every violation found, cite line numbers, explain the issue, provide corrected code, and reference the specific guideline section.

knowledge_base:
  opt_out: false
  learnings:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/BEST_PRACTICES.md"
      - "**/best_practices.md"
      - "**/Best_Practices.md"

reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  
  path_filters:
    - "!**/settings.json"
    - "!**/*.meta"
    - "!**/*.asset"
    - "!**/Library/**"
    - "!**/Temp/**"
    - "!**/Logs/**"
    - "!**/Packages/**"
    - "!**/ProjectSettings/**"
    - "!**/obj/**"
    - "!**/bin/**"
  
  path_instructions:
    - path: "**/*.cs"
      instructions: |
        Review this C# file comprehensively against ALL rules, principles, and guidelines documented in BEST_PRACTICES.md.
        
        Check every aspect of the code against every rule, principle, guideline, code example pattern, and requirement specified in BEST_PRACTICES.md. Be thorough and check for violations of every rule documented, regardless of which section it appears in.
        
        For each violation found, cite line numbers, explain the issue, provide corrected code, and reference the specific guideline section.
