# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

tone_instructions: Enforce ALL rules from BEST_PRACTICES.md. Check every section. Flag violations with line numbers, explanations, corrected code, and section references.

knowledge_base:
  opt_out: false
  learnings:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CodingStandards.md"

reviews:
  profile: assertive
  high_level_summary: true
  high_level_summary_placeholder: "Summary"
  auto_title_instructions: Generate concise PR titles that describe the main changes. Focus on what was added, fixed, or improved.
  auto_review:
    enabled: true
    drafts: false
  
  path_filters:
    - "!**/settings.json"
    - "!**/*.meta"
    - "!**/*.asset"
    - "!**/Library/**"
    - "!**/Temp/**"
    - "!**/Logs/**"
    - "!**/Packages/**"
    - "!**/ProjectSettings/**"
    - "!**/obj/**"
    - "!**/bin/**"