# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

tone_instructions: Enforce every registered guideline; cite sections, list line numbers, explain root causes, include corrected snippets, keep inline comments as Markdown checklists of each flaw.

knowledge_base:
  opt_out: false
  learnings:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CodingStandards.md"

reviews:
  profile: assertive
  high_level_summary: true
  high_level_summary_placeholder: "Pull Request Summary"
  auto_title_instructions: Generate concise PR titles that describe the main changes. Focus on what was added, fixed, or improved.
  collapse_walkthrough: true
  auto_review:
    enabled: false
    drafts: false
  
  path_filters:
    - "!**/settings.json"
    - "!**/*.meta"
    - "!**/*.asset"
    - "!**/Library/**"
    - "!**/Temp/**"
    - "!**/Logs/**"
    - "!**/Packages/**"
    - "!**/ProjectSettings/**"
    - "!**/obj/**"
    - "!**/bin/**"
